# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: FelisDiligens' blog
email: "felisdiligens@yahoo.com"
description: >- # this means to ignore newlines until "baseurl:"
    Just a place where I dump stuff...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://felisdiligens.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#theme: minima
remote_theme: jekyll/minima
plugins:
    - jekyll-feed
    - jekyll-remote-theme
show_excerpts: true

minima:
    skin: dark
    social_links:
        - title: GitHub
          platform: github
          user_url: "https://github.com/FelisDiligens"
        - title: NexusMods
          platform: nexusmods
          user_url: "https://www.nexusmods.com/fallout76/users/41275740"
        - title: npm
          platform: npm
          user_url: "https://www.npmjs.com/~felisdiligens"
        - title: Ko-fi
          platform: kofi
          user_url: "https://ko-fi.com/felisdiligens"
        - title: Joplin Forum
          platform: joplin
          user_url: "https://discourse.joplinapp.org/u/felisdiligens"
    disqus:
        shortname: felisdiligens-github-io

author:
    name: FelisDiligens
    email: "felisdiligens@yahoo.com"

header_pages:
  - about.md
  - posts.html

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
